# Generated by Django 5.0.1 on 2024-03-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_add_cart_product_add_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('Pastcode', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
