# Generated by Django 5.0.1 on 2024-04-01 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_billing_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='billing_address',
            new_name='billing_address1',
        ),
    ]
